# Generated by Django 5.2.6 on 2025-09-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_autor_comment_delete_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
