# Generated by Django 5.2.5 on 2025-09-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codinome', models.CharField(max_length=100)),
                ('nome_real', models.CharField(blank=True, max_length=100, null=True)),
                ('poder_principal', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('historia', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Villain',
                'verbose_name_plural': 'Villains',
            },
        ),
    ]
