# Generated by Django 5.2.5 on 2025-09-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villain',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_viloes/'),
        ),
        migrations.AddField(
            model_name='villain',
            name='nivel_ameaca',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20),
        ),
    ]
