# Generated by Django 5.2.5 on 2025-09-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='email_contato',
            field=models.EmailField(default='heroi@heroi.com', max_length=254, verbose_name='Email de contato'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='codinome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='poder_principal',
            field=models.CharField(max_length=200),
        ),
    ]
