# Generated by Django 5.2.5 on 2025-09-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_hero_email_contato_alter_hero_codinome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_herois/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='codinome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='poder_principal',
            field=models.CharField(max_length=100),
        ),
    ]
